# Generated by Django 5.1 on 2024-08-26 09:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dff55fb1-bbae-4ffc-95ba-bf40142c9451'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('29660593-ee6e-4b8f-9ae5-12b8c3f93930'), editable=False, primary_key=True, serialize=False),
        ),
    ]
